# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
<<<<<<< HEAD
title:            Intro to Data Science w/ R
description:      'How to think like a data scientist'
url:              https://tychen742.github.io/datascience
baseurl:          /datascience
=======
title:            Data Science w/ R
description:      'How to think like a data scientist'
url:              https://datascience.tychen.us/
baseurl:          
>>>>>>> 3a1cc916ac7f9b85e864e1f063319cfab1607429
email:            
feedbackurl:      docs.google.com
author:
  name:           'TY Chen' 
<<<<<<< HEAD
  url:            http://tychen.us/
=======
  url:            https://datascience.tychen.us/
>>>>>>> 3a1cc916ac7f9b85e864e1f063319cfab1607429

github:
  repo:           https://github.com/tychen742/datascience
  #               Be sure the 'Issues' feature is activated in 'Settings'
# theme:            minima
<<<<<<< HEAD
=======

theme: jekyll-theme-minimal
>>>>>>> 3a1cc916ac7f9b85e864e1f063319cfab1607429
