# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup

title:            Data Science with Python
description:      'How to think like a data scientist'
url:              https://datasciencepy.tychen.us/
baseurl:          
email:            tchen@business.fsu.edu
feedbackurl:      
author:
  name:           'TY Chen' 

  url:            https://tychen.us/

github:
  repo:           https://github.com/tychen742/dataSciencePy
  #               Be sure the 'Issues' feature is activated in 'Settings'
# theme:            minima
theme: jekyll-theme-minimal

